### ISSUE TITLE
moving the city/ item list from a hard coded HTML file to database

### ISSUE THREAD

**Issue by nadavshoshan** [beyond-io/givit#14]
since we want to avoid typo mistakes by our friend on their items requests we want to let them choose from  a fixed list

now, for testing, I hardcoded a list of cities and items.

@rotem-benzvi , after we will define the parameters for the gatherer component we will build a database for items and cities which we want to support.

**Comment by nadavshoshan** [comment]
I used Enum to limit the option of items/region

that has solved the problem

**Comment by liorsicd** [comment]
great job!!
