### ISSUE TITLE
change the create superuser aproach for our django-app

### ISSUE THREAD

**Issue by rotem-benzvi** [beyond-io/givit#15]
at this moment we create the superuser when we initial the app using 
we need to change it and do it via a migration, a better approach, and update the instructions in README.md
links for start:
https://stackoverflow.com/a/53555252/8243700
https://docs.djangoproject.com/en/3.0/topics/migrations/#data-migrations
https://docs.djangoproject.com/en/3.1/intro/tutorial02/

**Comment by liorsicd** [comment]
@nadavshoshan your last PR is answering this issue, right?

**Comment by nadavshoshan** [comment]
Not yet.
Rotem should upload the bootstrap.sh file first. Than we make sure that the
whole process works
