### ISSUE TITLE
implement virtualenv in our bootstrap process

### ISSUE THREAD

**Issue by rotem-benzvi** [beyond-io/givit#20]
our temporary solution right now don't include virtualenv and we install all packages directly on the vagrant using requirements our goal is to implement virtualenv in the bootstrap process.

useful link- 
https://docs.python.org/3/tutorial/venv.html

relevant PR -
https://github.com/beyond-io/givit/pull/16#issue-475737799

**Comment by liorsicd** [comment]
@rotem-benzvi so it's done?
