### ISSUE TITLE
update README.md with time zone explanations

### ISSUE THREAD

**Issue by rotem-benzvi** [beyond-io/givit#64]
# Set Timezone

for our Gatherer app we need to make sure that the timezone is set to ...

1. Before changing the time zone, you’ll need to find out the long name of the time zone you want to use. The time zone naming convention usually uses a “Region/City” format.

```
timedatectl list-timezones
sudo timedatectl set-timezone Asia/Jerusalem
timedatectl
```

**Comment by nadavshoshan** [comment]
done it
